### ISSUE TITLE
Set up repository on Github

### ISSUE THREAD

**Issue by diannakmm** [diannakmm/EmotionalSupportAnimal#1]
- [x] Create repository
- [x] Add collaborators
- [x] Set up Milestones
- [x] Set up Labels
- [x] Associate with Project

**Comment by MatthewZhu01** [comment]
Label Definitions

Easy: A problem or part of the project that is easy to fix (less than an hour)

Medium: A problem or part of the project that will take a while to finish (1 or 2 days)

Hard: A problem of part of the project that needs a lot of attention to fix. (More than a week)

Software: A problem related to coding

Hardware: A problem related to the properties of a electrical component

Design: A problem related to the design or wiring of each electrical component

Documentation: Something that should be documented for the future. Usually a problem that is reoccurring
