### ISSUE TITLE
Set up library files

### ISSUE THREAD

**Issue by diannakmm** [diannakmm/EmotionalSupportAnimal#18]
- [x] setup.py
- [x] EmotionalSupport.py
- [x] demo.py

**Comment by MatthewZhu01** [comment]
Any time a team member makes a change to the software library, test by:

```
sudo python3 setup.py install
python3 demo.py
```

For now, it should just say:

```
Software library for the EmotionalSupportAnimal project.

```

**Comment by MatthewZhu01** [comment]
See commit afb9e10

**Comment by diannakmm** [comment]
software library test successful
